<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Tillad brugere med indlæg til at ændre deres brugernavn:',
		'allow_close_questions' => 'Tillad spørgsmål, at blive manuelt lukket:',
		'allow_login_email_only' => 'Kun logge ind via e-mail-adresse (ikke brugernavn):', 
		'allow_multi_answers' => 'Tillad flere svar per bruger:',
		'allow_no_category' => 'Tillad spørgsmål med ingen kategori',
		'allow_no_sub_category' => 'Tillad spørgsmål med en kategori, men ingen underkategorier',
		'allow_private_messages' => 'Aktiver private beskeder mellem brugere:',
		'allow_self_answer' => 'Tillad brugere at svare på deres eget spørgsmål:',
		'allow_view_q_bots' => 'Tillad søgemaskiner at se spørgsmål siderne',
		'avatar_allow_gravatar' => 'Tillad ^1Gravatar^2 avatars:',
		'avatar_allow_upload' => 'Tillad brugere at uploade avatars:',
		'avatar_default_show' => 'Standard avatar:',
		'avatar_profile_size' => 'Avatar størrelse på brugerens profil side:',
		'avatar_q_list_size' => 'Avatar størrelse på spørgsmål lister:',
		'avatar_q_page_a_size' => 'Avatar størrelse på svar:',
		'avatar_q_page_c_size' => 'Avatar størrelse på kommentarer:',
		'avatar_q_page_q_size' => 'Avatar størrelse på spørgsmål:',
		'avatar_store_size' => 'Den maksimale størrelse til lagring af avatarer:',
		'avatar_users_size' => 'Avatar størrelse på top bruger side:',
		'block_bad_words' => 'Censurerede ord - adskilt med mellemrum eller kommaer:',
		'block_ips_write' => 'Blokerede IP-adresser - adskilt med mellemrum eller kommaer:',
		'captcha_module' => 'Brug captcha-modul:',
		'captcha_on_anon_post' => 'Brug captcha for anonyme indlæg:',
		'captcha_on_feedback' => 'Brug captcha på feedback-formularen:',
		'captcha_on_register' => 'Brug captcha for brugerregistrering:',
		'captcha_on_reset_password' => 'Brug captcha på nulstil password formular:',
		'captcha_on_unconfirmed' => 'Brug captcha, hvis e-mail ikke bekræftet:',
		'columns_tags' => 'Kolonner på Tags side:',
		'columns_users' => 'Kolonner på Brugere side:',
		'comment_on_as' => 'Tillad kommentarer til svar:',
		'comment_on_qs' => 'Tillad kommentarer til spørgsmål:',
		'confirm_user_emails' => 'Anmodning bekræftelse af brugerens e-mails:',
		'confirm_user_required' => 'Nye brugere skal udfylde bekræftelse:',
		'custom_home_content' => 'Hjemmeside indhold - HTML tilladt:',
		'custom_home_heading' => 'Hjemmeside overskrift:',
		'default_privacy' => 'Privacy: Din email adresse vil ikke blive delt eller solgt til tredjepart.',
		'default_sidebar' => 'Velkommen til ^, hvor du kan stille spørgsmål og få svar fra andre medlemmer af fællesskabet.',
		'default_subject' => 'En besked fra ^',
		'default_suffix' => 'Q&A',
		'do_ask_check_qs' => 'Check for lignende spørgsmål, når man spørger:',
		'do_close_on_select' => 'Luk spørgsmål med et udvalgt svar:',
		'do_complete_tags' => 'Vis matchende tags mens du skriver:',
		'do_count_q_views' => 'Tæl antallet af spørgsmåls visninger:',
		'do_example_tags' => 'Vis eksemple tags baseret på spørgsmål:',
		'editor_for_as' => 'Standard editor til svar:',
		'editor_for_cs' => 'Standard editor til kommentarer:',
		'editor_for_qs' => 'Standard editor til spørgsmål:',
		'email_privacy' => 'Beskyttelse af personlige note til e-mail adresser - HTML tilladt:',
		'extra_field_active' => 'Brugerdefineret felt for ekstra information om spørgsmåls formular:',
		'extra_field_display_label' => 'Vis ekstra information om spørgsmåls sider med etiket:',
		'extra_field_display' => 'Vis ekstra information om spørgsmåls sider',
		'feed_for_activity' => 'Feed til seneste aktivitet:',
		'feed_for_hot' => 'Feed for hot spørgsmål:',
		'feed_for_qa' => 'Feed til de seneste spørgsmål og svar:',
		'feed_for_questions' => 'Feed til de seneste spørgsmål:',
		'feed_for_search' => 'Feeds for søgeresultat:',
		'feed_for_tag_qs' => 'Feed for hver tag\'s spørgsmål:',
		'feed_for_unanswered' => 'Feed for ubesvarede spørgsmål:',
		'feed_full_text' => 'Inkludere fuld tekst i feeds:',
		'feed_number_items' => 'Maksimal længde af feeds:',
		'feed_per_category' => 'Individuelle feeds per kategori:',
		'feedback_email' => 'E-mail-adresse for admin beskeder - ikke vist til brugerne:',
		'feedback_enabled' => 'Giv en side for brugerne for at sende feedback',
		'flagging_hide_after' => 'Automatisk skjule indlæg når de når til:',
		'flagging_notify_every' => 'Email mig igen efter hver ekstra:',
		'flagging_notify_first' => 'E-mail mig, hvis et indlæg modtager:',
		'flagging_of_posts' => 'Tillad indlæg der skal flagged:',
		'follow_on_as' => 'Tillad spørgsmål at være relateret til svar:',
		'from_email' => 'Sender adresse efter indlæg fra siden:',
		'hot_weight_a_age' => 'Spørgsmål har et nyt svar:',
		'hot_weight_answers' => 'Spørgsmål har mange svar:',
		'hot_weight_q_age' => 'Spørgsmål er nyt:',
		'hot_weight_views' => 'Spørgsmål har mange visninger:',
		'hot_weight_votes' => 'Spørgsmål har mange op-stemmer:',
		'links_in_new_window' => 'Åbn linket webadresser i et nyt vindue:',
		'logo_height' => 'Logo højde:',
		'logo_show' => 'Vis et logo billede i sidehovedet',
		'logo_url' => 'URL til logo - absolute eller relative til Q2A roden:',
		'logo_width' => 'Logo bredde:',
		'mailing_body' => 'Body tekst:',
		'mailing_enabled' => 'Aktiver masseforsendelser til alle brugere',
		'mailing_from_email' => 'Fra e-mail adresse:',
		'mailing_from_name' => 'Fra navne:',
		'mailing_per_minute' => 'Maksimal udsendelsesfrekvens:',
		'mailing_subject' => 'Emnelinje:',
		'match_1' => 'Smallest',
		'match_2' => 'Smallere',
		'match_3' => 'Standard',
		'match_4' => 'Bredere',
		'match_5' => 'Bredest',
		'match_ask_check_qs' => 'Lignende spørgsmål matchende:',
		'match_example_tags' => 'Eksempel tags matchende:',
		'match_related_qs' => 'Relaterede spørgsmål matchende:',
		'max_len_q_title' => 'Den maksimale længde af spørgsmål titel:',
		'max_num_q_tags' => 'Maksimalt antal tags:',
		'max_rate_ip_as' => 'Bedøm grænse for at tilføje svar:',
		'max_rate_ip_cs' => 'Bedøm grænse for at skrive kommentarer:',
		'max_rate_ip_flags' => 'Bedøm grænse for flagging indlæg:',
		'max_rate_ip_logins' => 'Bedøm grænse for at logge ind:',
		'max_rate_ip_messages' => 'Bedøm grænse for at sende private beskeder:',
		'max_rate_ip_qs' => 'Bedøm grænse for at stille spørgsmål:',
		'max_rate_ip_registers' => 'Bedøm grænse for bruger registreringer:',
		'max_rate_ip_uploads' => 'Bedøm grænse for uploading af filer:',
		'max_rate_ip_votes' => 'Bedøm grænse for afstemning:',
		'max_rate_user_as' => 'Maksimum svar pr. bruger pr. time:',
		'max_rate_user_cs' => 'Maksimum kommentarer pr. bruger pr. time:',
		'max_rate_user_flags' => 'Maksimum flags pr. bruger pr. time:',
		'max_rate_user_messages' => 'Maksimum private beskeder pr. bruger pr. time:',
		'max_rate_user_qs' => 'Maksimum spørgsmål pr. bruger pr. time:',
		'max_rate_user_uploads' => 'Maksimum uploads pr. bruger pr. time:',
		'max_rate_user_votes' => 'Maksimum stemmer pr. bruger pr. time:',
		'min_len_a_content' => 'Minimum længde af svar:',
		'min_len_c_content' => 'Minimum længde af kommentar:',
		'min_len_q_content' => 'Minimum længde af spørgsmåls body:',
		'min_len_q_title' => 'Minimum længde af spørgsmåls titel:',
		'min_num_q_tags' => 'Minimum længde af tags:',
		'moderate_anon_post' => 'Brug moderation for anonyme indlæg:',
		'moderate_by_points' => 'Brug moderation for brugere med få point:',
		'moderate_notify_admin' => 'Email mig når et indlæg brug for moderation:',
		'moderate_points_limit' => 'Brug moderation for brugere med mindre end:',
		'moderate_unconfirmed' => 'Brug moderation, hvis e-mail ikke bekræftet:',
		'neat_urls' => 'URL struktur:',
		'notify_admin_q_post' => 'E-mail til denne adresse når et spørgsmål er blevet stillet',
		'notify_users_default' => 'Kontroller e-mail meddelelse box som standard:',
		'option_default' => 'Standard',
		'page_size_activity' => 'Længde for aktivitet siden:',
		'page_size_ask_check_qs' => 'Maksimalt lignende spørgsmål for at vise:',
		'page_size_ask_tags' => 'Maksimum tag tips til at vise:',
		'page_size_home' => 'Længde af Q&A side:',
		'page_size_hot_qs' => 'Længe af Hot! side:',
		'page_size_q_as' => 'Maksimum svar pr. side:',
		'page_size_qs' => 'Længde af spørgsmåls side:',
		'page_size_related_qs' => 'Maksimum relateret spørgsmål:',
		'page_size_search' => 'Søgeresultat pr. side:',
		'page_size_tag_qs' => 'Spørgsmål på hver tag side:',
		'page_size_tags' => 'Længde af Tags side:',
		'page_size_una_qs' => 'Længde af ubesvaret side:',
		'page_size_users' => 'Længde af brugere side:',
		'pages_prev_next' => 'Links til forrige/næste sider:',
		'permit_admins' => 'Administratorer',
		'permit_all' => 'Enhver',
		'permit_block' => 'Blokering eller fjernelse af blokering bruger eller IPer:',
		'permit_confirmed' => 'Registrerede brugere med e-mail bekræftet',
		'permit_create_admins' => 'Opret administrator:',
		'permit_create_eds_mods' => 'Opret redaktører og moderatorere:',
		'permit_create_experts' => 'Opret eksperter:',
		'permit_delete_users' => 'Slet brugere:',
		'permit_editors' => 'Redaktører, Moderatore, Administratore',
		'permit_experts' => 'Eksperter, Redaktører, Moderatorere, Administratore',
		'permit_moderators' => 'Moderatorere og administratore',
		'permit_points_confirmed' => 'Registrerede & E-mail bekræftet & nok point',
		'permit_points' => 'Registrerede brugere med nok point',
		'permit_see_emails' => 'Viser brugerens e-mail-adresser:',
		'permit_supers' => 'Super Administratore',
		'permit_users' => 'Registrerede brugere',
		'place_full_below_content' => 'Fuld bredde - Under indhold',
		'place_full_below_footer' => 'Fuld bredde - Under footer',
		'place_full_below_nav' => 'Fuld bredde - Under navigation',
		'place_full_top' => 'Fuld bredde - Øverst på siden',
		'place_main_below_lists' => 'Hovedområde - Under listerne',
		'place_main_below_title' => 'Hovedområde - Under titlen',
		'place_main_bottom' => 'Hovedområde - Bund',
		'place_main_top' => 'Hovedområde - Øverst',
		'place_side_below_categories' => 'Side panel - Under kategorier',
		'place_side_below_sidebar' => 'Side panel - Under sidebar bols',
		'place_side_last' => 'Side panel - Sidst',
		'place_side_top' => 'Side panel - Øverst',
		'points_a_selected' => 'Dit svar er valgt som det bedste:',
		'points_a_voted_max_gain' => 'Grænse fra op stemmer på hvert svar:',
		'points_a_voted_max_loss' => 'Grænse fra ned stemmer på hvert svar:',
		'points_base' => 'Tilføj for alle brugere:',
		'points_multiple' => 'Multiplicer alle punkter:',
		'points_per_a_voted_down' => 'Pr. ned stemme på dit svar:',
		'points_per_a_voted_up' => 'Pr. op stemme på dit svar:',
		'points_per_q_voted_down' => 'Pr. ned stemme på dit spørgsmål:',
		'points_per_q_voted_up' => 'Pr. op stemme på dit spørgsmål:',
		'points_post_a' => 'Udgiv et svar:',
		'points_post_q' => 'Udgiv et spørgsmål:',
		'points_q_voted_max_gain' => 'Grænse fra op stemme på hvert spørgsmål:',
		'points_q_voted_max_loss' => 'Grænse fra ned stemme på hvert spørgsmål:',
		'points_select_a' => 'Valg af et svar til dit spørgsmål:',
		'points_vote_down_a' => 'Stemmer et svaret ned:',
		'points_vote_down_q' => 'Stemmer et spørgsmål ned:',
		'points_vote_up_a' => 'Stemmer et svar op:',
		'points_vote_up_q' => 'Stemmer et spørgsmål op:',
		'q_urls_remove_accents' => 'Fjern accenter fra spørgsmål URLs:',
		'q_urls_title_length' => 'Spørgsmåls længde af URL i titlen:',
		'search_module' => 'Brug søgemodul:',
		'show_a_form_immediate' => 'Vis svar formularen umiddelbart:',
		'show_always' => 'Altid',
		'show_c_reply_buttons' => 'Vis svar knap på kommentarer:',
		'show_custom_answer' => 'Brugerdefineret besked på svar form - HTML tilladt:',
		'show_custom_ask' => 'Brugerdefineret besked på spørge form - HTML tilladt:',
		'show_custom_comment' => 'Brugerdefineret besked på kommentar form - HTML tilladt:',
		'show_custom_footer' => 'Brugerdefineret HTML nederst på hver side:',
		'show_custom_header' => 'Brugerdefineret HTML øverst på hver side:',
		'show_custom_home' => 'Brugerdefineret indhold på hjemmesiden i stedet for Q & A',
		'show_custom_in_head' => 'Brugerdefineret HTML i <HEAD> sektion af hver side:',
		'show_custom_register' => 'Brugerdefineret besked på register form - HTML tilladt:',
		'show_custom_sidebar' => 'Brugerdefineret HTML i sidebjælken i hver side:',
		'show_custom_sidepanel' => 'Brugerdefineret HTML i sidepanelet på hver side:',
		'show_custom_welcome' => 'Brugerdefineret besked i e-mail sendt til nye registrerede brugere:',
		'show_fewer_cs_count' => 'Hvis delvist skjult, vis de seneste:',
		'show_fewer_cs_from' => 'Delvist skjule kommentarer, hvis mere end:',
		'show_full_date_days' => 'Vis fuld dato efter:',
		'show_home_description' => 'Inkludere <META> description for hjemmesidens forside:',
		'show_if_no_as' => 'Hvis ingen svar',
		'show_message_history' => 'Gem og vis private besked historik:',
		'show_never' => 'Aldrig',
		'show_notice_visitor' => 'Bemærkning øverst for første gang besøgende - HTML tilladt:',
		'show_notice_welcome' => 'Bemærkning øverst til nye registrerede brugere - HTML tilladt:',
		'show_selected_first' => 'Flyt valgte svar til toppen:',
		'show_url_links' => 'Find og link URLs i indlæg:',
		'show_user_points' => 'Vis point ved siden af brugernavne:',
		'show_user_titles' => 'Vis titler ved siden af brugernavne:',
		'show_view_counts' => 'Vis antal af visninger i spørgsmåls listen:',
		'show_when_created' => 'Vis alder af bruger indlæg:',
		'site_language' => 'Side sprog:',
		'site_maintenance' => 'Tag hjemmeside ned for midlertidig vedligeholdelse',
		'site_theme_mobile' => 'Tema til mobiler:',
		'site_theme' => 'Side tema:',
		'site_title' => 'Q&A side navn:',
		'site_url' => 'Foretrukken webadresse URL:',
		'smtp_active' => 'Send email via SMTP i stedet for local mail',
		'smtp_address' => 'SMTP server adresse:',
		'smtp_authenticate' => 'Send SMTP brugernavn og adgangskode',
		'smtp_password' => 'SMTP adgangskide:',
		'smtp_port' => 'SMTP server port:',
		'smtp_secure_none' => 'Ingen',
		'smtp_secure' => 'SMTP secure connection:',
		'smtp_username' => 'SMTP brugernavn:',
		'sort_answers_by' => 'Sortere svar af:',
		'sort_time' => 'Tid',
		'sort_votes' => 'Stemmer',
		'suspend_register_users' => 'Midlertidigt suspendere nye brugerkonti:',
		'tag_separator_comma' => 'Brug komma som den eneste tag separatoren:',
		'tags_or_categories' => 'Spørgsmål klassificering:',
		'votes_separated' => 'Vis adskille op og ned stemmer:',
		'voting_on_as' => 'Tillad stemme på svar:',
		'voting_on_q_page_only' => 'Tillad afstemning om spørgsmåls side kun:',
		'voting_on_qs' => 'Tillad at stemme på spørgsmål:',
		'allow_user_walls' => "Tillad indlæg på profil vægge:",
		'approve_user_required' => "Alle nye brugere skal godkendes:",
		'avatar_message_list_size' => "Avatar størrelse på besked lister:",
		'captcha_on_unapproved' => "Brug CAPTCHA hvis brugeren ikke er godkendt:",
		'moderate_edited_again' => "Genmoderer indlæg efter redigering:",
		'moderate_unapproved' => "Brug moderering hvis brugeren ikke er godkendt:",
		'moderate_update_time' => "Tidsvisning af modererede indlæg:",
		'moderate_users' => "Aktiver moderering (godkendelse) af brugere:",
		'page_size_wall' => "Væg indlæg per side:",
		'permit_approve_users' => "Godkend registrerede brugere:",
		'permit_approved' => "Kun godkendte brugere",
		'permit_approved_points' => "Godkendte brugere med tilstrækkelige point",
		'register_notify_admin' => "Send en e-mail når en ny bruger registreres:",
		'show_view_count_q_page' => "Vis visnings-tæller på spørgsmålssider:",
		'time_approved' => "Klokkeslet godkendt",
		'time_written' => "Klokkeslet skrevet",		
		'allow_anonymous_naming' => "Tillad anonyme brugere at angive deres navn:",
		'allow_close_own_questions' => "Tillad brugere at lukke deres egne spørgsmål:",
		'block_bad_usernames' => "Forbudte brugernavne - adskil med mellemrum eller komma:",
		'caching_catwidget_time' => "Cache kategori widget for:",
		'caching_enabled' => "Muliggør caching:",
		'caching_driver' => "Caching driver",
		'caching_filesystem' => "Filsystem",
		'caching_memcached' => "Memcached",
		'caching_q_start' => "Start caching spørgsmål efter:",
		'caching_q_time' => "Cache spørgsmål sider for :",
		'caching_qlist_time' => "Cache spørgsmålsliste for:",
		'default_terms' => "I tilslutter mig ^ Betingelser og Vilkårs politikken",
		'minify_html' => "Minimer HTML:",
		'page_size_pms' => "Private beskeder pr side:",
		'place_side_low' => "Sidepanel - lav",
		'points_c_voted_max_gain' => "Grænse for upvotes på hver kommentar:",
		'points_c_voted_max_loss' => "Grænse for downvotes for hver kommentar:",
		'points_per_c_voted_down' => "Per downvote på din kommentar:",
		'points_per_c_voted_up' => "Per upvote på din kommentar:",
		'recalc_hotness_q_view' => "Genberegn intensitet ved hvert spørgsmålsside visning:",
		'show_compact_numbers' => "Vis kompakte tal (f.eks. 1.3k):",
		'show_post_update_meta' => "Vis redigeringer/opdateringer i indlægs meta:",
		'show_register_terms' => "Betinglser og Vilkårs flueben på registreringssiden - HTML tilladt:",
		'site_text_direction' => "Tekstretning for siden:",
		'use_microdata' => "Brug schema.org microdata:",
		'voting_on_cs' => "Tillad voteringer på kommentarer:",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
