<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-question.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Svar',
		'a_convert_to_c_on' => 'Konverter dette svar til en kommentar til:',
		'a_convert_to_c' => 'Konverter dette svar til en kommentar',
		'a_convert_warn_cs' => 'Warning: Denne konversion kan ikke blive tilbageført og vil også flytte dets svar\'s kommentarer.',
		'a_convert_warn' => 'Warning: Denne konversion kan ikke blive tilbageført.',
		'a_notify_email' => 'Email mig på denne adresse, hvis mit svar er valgt eller kommenteret på:',
		'a_notify_label' => 'E-mail mig, hvis mit svar er valgt eller kommenteret på',
		'a_notify_x_label' => 'Email mig (^) hvis mit svar er valgt eller kommenteret på',
		'a_waiting_your_approval' => 'Dette svar er venter på din godkendelse',
		'a_your_waiting_approval' => 'Dit svar vil blive kontrolleret og godkendt inden længe.',
		'add_answer_button' => 'Tilføj svar',
		'add_comment_button' => 'Tilføj kommentar',
		'add_q_favorites' => 'Tilføj dette spørgsmål til mine favoritter',
		'answer_button' => 'svar',
		'answer_limit' => 'For mange svar modtaget - prøv igen senere',
		'answer_must_confirm' => 'Venligst ^5bekræft din e-mail adresse^6 for at svare på dette spørgsmål.',
		'answer_must_login' => 'Venligst ^1log ind^2 eller ^3registrere^4 for at svare på dette spørgsmål.',
		'answer_q_popup' => 'Besvar dette spørgsmål',
		'approve_button' => 'godkend',
		'ask_button' => 'Stil et spørgsmål',
		'ask_follow_from_a' => 'Dit spørgsmål vil være relateret til dette svar:',
		'ask_follow_title' => 'Stil et relateret spørgsmål',
		'ask_limit' => 'For mange spørgsmål modtaget - prøv igen senere',
		'ask_must_confirm' => 'Venligst ^5bekræft din email adresse^6 for at stille et spørgsmål.',
		'ask_must_login' => 'Venligst ^1log ind^2 eller ^3registere^4 for at stille et spørgsmål.',
		'ask_same_q' => 'Før du fortsætter, bedes du tjekke dit spørgsmål er blevet stillet i forvejen:',
		'ask_title' => 'Stil et spørgsmål',
		'c_notify_email' => 'Email mig på denne adresse, hvis en kommentar tilføjes efter mit:',
		'c_notify_label' => 'E-mail mig, hvis en kommentar tilføjes efter mit',
		'c_notify_x_label' => 'Email mig (^) hvis en kommentar er tilføjet efter mit',
		'c_waiting_your_approval' => 'Denne kommentar afventer din godkendelse',
		'c_your_waiting_approval' => 'Din kommentar vil blive tjekket og godkendt inden længe.',
		'category_js_note' => 'For at vælge en kategori, skal du aktivere Javascript i din web browser.',
		'category_required' => 'Venligst vælg en kategori',
		'claim_button' => 'Jeg skrev dette',
		'clear_flags_button' => 'Fjern flags',
		'clear_flags_popup' => 'Fjern flags af alle brugere',
		'close_button' => 'luk',
		'close_duplicate_error' => 'Det duplikerde spørgsmål kunne ikke findes - Prøv at indtaste nummeret fra et andet spørgsmål URL, e.g. 123.',
		'close_duplicate' => 'Dette er en kopi af et andet spørgsmål',
		'close_form_button' => 'Luk spørgsmål',
		'close_form_title' => 'Luk dette spørgsmål',
		'close_original_note' => 'Du kan også indtaste spørgsmålets nummer fra URL, e.g. 123.',
		'close_original_title' => 'URL af det oprindelige spørgsmål:',
		'close_q_popup' => 'Luk dette spørgsmål for nye svar',
		'close_reason_title' => 'Årsag til lukning af dette spørgsmål:',
		'closed_as_duplicate' => 'lukket som en kopi af:',
		'closed_with_note' => 'lukket med noten:',
		'comment_a_popup' => 'Tilføj en kommentar til dette svar',
		'comment_button' => 'kommentar',
		'comment_limit' => 'For mange kommentarer modtaget - venligst prøv igen senere',
		'comment_must_confirm' => 'Venligst ^5bekræft din e-mail adresse^6 for at tilføje en kommentar.',
		'comment_must_login' => 'Venligst ^1log ind^2 eller ^3registere^4 for at tilføje en kommentar.',
		'comment_on_a' => 'På svar: ',
		'comment_on_q' => 'På spørgsmål: ',
		'comment_q_popup' => 'Tilføj en kommentar til dette spørgsmål',
		'delete_a_popup' => 'Slet dette svar permanent',
		'delete_button' => 'slet',
		'delete_c_popup' => 'Slet denne kommentar permanent',
		'delete_q_popup' => 'Slet dette spørgsmål permanent',
		'duplicate_content' => 'Din indsendelse ser ud til at være en dublet.',
		'edit_a_popup' => 'Redigere dette svar',
		'edit_a_title' => 'Redigere svar',
		'edit_button' => 'redigere',
		'edit_c_popup' => 'Redigere denne kommentar',
		'edit_c_title' => 'Redigere kommentar',
		'edit_must_confirm' => 'Venligst ^5bekræft din e-mail adresse^6 for at redigere dette.',
		'edit_must_login' => 'Venligst ^1log ind^2 eller ^3registere^4 for at redigere dette.',
		'edit_q_popup' => 'Redigere dette spørgsmål',
		'edit_q_title' => 'Redigere spørgsmål',
		'example_tags' => 'Eksempel tags: ',
		'flag_a_popup' => 'Anmeld dette svar som spam eller upassende',
		'flag_button' => 'anmeld',
		'flag_c_popup' => 'Anmeld denne kommentar som spam eller upassende',
		'flag_hide_button' => 'anmeld og skjul',
		'flag_limit' => 'For mange indlæg anmeldt - prøv igen om en time',
		'flag_must_confirm' => 'Venligst ^5bekræft din e-mail adresse^6 for at anmelde indlæg.',
		'flag_must_login' => 'Venligst ^1log ind^2 eller ^3registere^4 for at anmelde indlæg.',
		'flag_not_allowed' => 'Du kan ikke anmelde dette',
		'flag_q_popup' => 'Flag dette spørgsmål som spam eller upassende',
		'follow_a_popup' => 'Stil et nyt spørgsmål relateret til dette svar',
		'follow_button' => 'stil relateret spørgsmål',
		'follows_a' => 'relateret til et svar for:',
		'follows_q' => 'omkring dette spørgsmål:',
		'hide_a_popup' => 'Skjul dette svar',
		'hide_button' => 'skjul',
		'hide_c_popup' => 'Skjul denne kommentar',
		'hide_q_popup' => 'Skjul dette spørgsmål',
		'matching_tags' => 'Matchende tags: ',
		'max_tags_x' => 'Et maksimum af ^ tags er tilladt',
		'min_tags_x' => 'Venligst giv mindst ^ tag/s',
		'notify_email_note' => 'Privacy: Din email adresse vil kun blive brugt til at sende disse meddelelser.',
		'q_category_label' => 'Kategori:',
		'q_content_label' => 'Flere oplysninger til spørgsmålet:',
		'q_hidden_author' => 'Dette spørgsmål er blevet skjult af forfatteren',
		'q_hidden_flagged' => 'Dette spørgsmål er blevet flagged og skjult',
		'q_hidden_other' => 'Dette spørgsmål er blevet skjult',
		'q_notify_email' => 'Email mig på denne adresse, hvis mit spørgsmål er besvaret eller kommenteret på:',
		'q_notify_label' => 'E-mail mig, hvis mit spørgsmål er besvaret eller kommenteret på',
		'q_notify_x_label' => 'Email mig (^) hvis mit spørgsmål er blevet besvaret eller kommenteret på',
		'q_tags_comma_label' => 'Tags - brug komma (,) som separator:',
		'q_tags_label' => 'Tags - Brug bindestreger til at kombinere ord:',
		'q_title_label' => 'Spørgsmålet i en sætning:',
		'q_waiting_approval' => 'Dette spørgsmål afventer godkendelse',
		'q_waiting_your_approval' => 'Dette spørgsmål afventer din godkendelse',
		'q_your_waiting_approval' => 'Dit spørgsmål vil blive tjekket og godkendt inden længe.',
		'recat_button' => 'gen-kategorisere',
		'recat_popup' => 'Ændre dette spørgsmål\'s kategori',
		'recat_q_title' => 'Gen-kategorisere spørgsmål',
		'reject_button' => 'afvis',
		'remove_q_favorites' => 'Fjern dette spørgsmål fra mine favoritter',
		'reopen_button' => 'gen-åben',
		'reply_button' => 'besvar',
		'reply_c_popup' => 'Besvar til denne kommentar',
		'reshow_button' => 'gen-vis',
		'retag_button' => 're-tag',
		'retag_cat_popup' => 'Ændre dette spørgsmål\'s kategori eller tags',
		'retag_popup' => 'Ændre dette spørgsmål\'s tags',
		'retag_q_title' => 'Re-tag spørgsmål',
		'select_popup' => 'Klik for at vælg som bedste svar',
		'select_text' => 'Bedste svar',
		'show_1_comment' => 'Vis 1 kommentar',
		'show_1_previous_comment' => 'Vis 1 forrig kommentar',
		'show_x_comments' => 'Vis ^ kommentarer',
		'show_x_previous_comments' => 'Vis ^ forrige kommentarer',
		'unflag_button' => 'un-flag',
		'unflag_popup' => 'Fjern det flag du har tilføjet',
		'unselect_popup' => 'Klik for at fjerne valg',
		'x_answers_title' => '^ Besvarelser',
		'your_answer_title' => 'Dit svar',
		'your_comment_a' => 'Din kommentar på dette svar:',
		'your_comment_q' => 'Din kommentar på dette spørgsmål:',
		'anon_name_label' => "Dit viste navn (frivilligt):",
		'answer_must_be_approved' => "Din konto skal være godkendt før du kan besvare et spørgsmål. Vent venligst eller ^1tilføj mere information^2.",
		'ask_must_be_approved' => "Din konto skal være godkendt før du kan stille et spørgsmål. Vent venligst eller ^1tilføj mere information^2.",
		'category_ask_not_allowed' => "Du har ikke rettigheder til at stille spørgsmål i denne kategori",
		'comment_must_be_approved' => "Din konto skal være godkendt for at du kan tilføje en kommentar. Vent venligst eller ^1tilføj mere information^2.",
		'save_silent_label' => "Gem lydløst for at skjule at dette var redigeret",		
		'approve_a_popup' => "Godkend dette svar",
		'approve_c_popup' => "Godkend denne kommentar",
		'approve_q_popup' => "Godkend dette spørgsmål",
		'claim_a_popup' => "Tilføj dette svar til din brugerkonto",
		'claim_c_popup' => "Tilføj dette spørgsmål til din brugerkonto",
		'claim_q_popup' => "Tilføj dette spørgsmål til din brugerkonto",
		'reject_a_popup' => "Afvis dette svar",
		'reject_c_popup' => "Afvis denne kommentar",
		'reject_q_popup' => "Afvis dette spørgsmål",
		'reopen_q_popup' => "Genåben dette spørgsmål",
		'reshow_a_popup' => "Vis dette svar igen",
		'reshow_c_popup' => "Vis denne kommentar igen",
		'reshow_q_popup' => "Vis dette spørgsmål igen",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
