<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Aktive widgets:',
		'add_category_button' => 'Tilføj kategori',
		'add_field_button' => 'Tilføj felt',
		'add_link_button' => 'Tilføj link',
		'add_link_link' => ' - ^1tilføj link^2',
		'add_new_field' => 'Tilføj nyt felt',
		'add_new_title' => 'Tilføj ny titel',
		'add_page_button' => 'Tilføj side',
		'add_title_button' => 'Tilføj titel',
		'add_widget_button' => 'Tilføj Widget',
		'add_widget_link' => ' - ^1tilføj widget^2',
		'admin_title' => 'Administration center',
		'after_footer' => 'Efter links i foden',
		'after_main_menu' => 'Efter tabs i toppen',
		'after_x_tab' => 'Efter "^" tab',
		'after_x' => 'Efter "^"',
		'moderate_title' => 'Moderer',
		'basic_editor' => 'Basic Editor',
		'before_main_menu' => 'Før tabs i toppen',
		'block_ips_note' => 'Brug en bindestreg til intervaller eller * for at matche alle numre. Eksempler: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Brug en * for at matche alle bogstaver. Eksempler: doh (matcher de præcise ord dog), doh* (vil matche doh og dohh), do*h (vil matche doh, dooh, dough).',
		'cancel_mailing_button' => 'Anuller mailudsendelse',
		'categories_introduction' => 'For at komme i gang med kategorier, klik da på \'Tilføj kategori\' knappen.',
		'categories_not_shown' => 'Nogle spørgsmål har kategorier, som ikke vil blive vist.',
		'categories_title' => 'Kategorier',
		'categories' => 'Kategorier',
		'category_add_sub' => 'tilføj under-kategori',
		'category_added' => 'Kategori tilføjet',
		'category_already_used' => 'Dette er allerede brugt af en kategori',
		'category_default_slug' => 'kategori-^',
		'category_description' => 'Valgfri kategori beskrivelse:',
		'category_max_depth_x' => 'Nogle indstillinger kan være skjult for at forhindre en kategori går dybere end ^ niveauer.',
		'category_move_parent' => 'flytter til anden forælder',
		'category_name_first' => 'Navn på første kategori:',
		'category_name' => 'Kategori navn:',
		'category_no_add_subs_x' => 'Denne kategori kan ikke have underkategorier, fordi det allerede er ^ niveauer ned.',
		'category_no_delete_subs' => 'Denne kategori kan ikke slettes, fordi det har en underkategori.',
		'category_no_sub_error' => '^q spørgsmål/s i denne kategori har ingen underkategorier - ^1set underkategori^2',
		'category_no_sub_to' => 'Flyt spørgsmål i ^ uden sub-kategori til:',
		'category_no_subs' => 'Ingen',
		'category_none_error' => '^q spørgsmål/s har i øjeblikket ingen kategori - ^1set kategori^2',
		'category_none_to' => 'Flyt spørgsmål uden kategori:',
		'category_parent' => 'Forældre kategori:',
		'category_saved' => 'Kategori gemt',
		'category_slug' => 'Kategori slug - URL fragment:',
		'category_subs' => 'Underkategorier:',
		'category_top_level' => 'Ingen forældre (øverste niveau)',
		'characters' => 'karakter',
		'check_language_suffix' => ' - ^1tjek sprog fil^2',
		'click_name_edit' => 'Brugerdefinerede sider eller links:',
		'database_cleanup' => 'Database clean-up operationer',
		'delete_category_reassign' => 'Slet denne kategori og tildel dens spørgsmål til:',
		'delete_category' => 'Slet denne kategori',
		'delete_field' => 'Slet dette felt',
		'delete_hidden_complete' => 'Alle skjulte stillinger uden pårørende er blevet slettet',
		'delete_hidden_note' => ' - alle skjulte spørgsmål, svar og kommentarer uden pårørende',
		'delete_hidden' => 'Slet skujlt indlæg',
		'delete_link' => 'Slet dette link',
		'delete_page' => 'Slet denne side',
		'delete_stop' => 'Stop sletning',
		'delete_title' => 'Slet denne titel',
		'delete_widget_position' => 'Slet denne widget fra denne position',
		'edit_custom_page' => 'Rediger brugerdefineret side',
		'edit_field' => ' - ^1rediger felt^2',
		'edit_link' => ' - ^1rediger link^2',
		'edit_page' => ' - ^1rediger side^2',
		'edit_title' => ' - ^1rediger titel^2',
		'emails_per_minute' => 'emails pr. minut',
		'emails_title' => 'Emails',
		'feed_link_example' => 'Eksempel feed',
		'feed_link' => 'Feed',
		'feeds_title' => 'RSS feeds',
		'field_link_url' => 'Linket URL',
		'field_multi_line' => 'Flere tekstlinjer',
		'field_name' => 'Felt navn:',
		'field_single_line' => 'Enkelt tekstlinje',
		'field_type' => 'Type af indhold:',
		'first' => 'Første',
		'flagged_title' => 'Flagged',
		'from_anon' => 'fra anonym:',
		'from_users' => 'fra brugere:',
		'general_title' => 'General',
		'hidden_answers_deleted' => 'Slettet ^1 af ^2 skjulte svar uden pårørende...',
		'hidden_comments_deleted' => 'Slettet ^1 af ^2 skjulte kommentarer...',
		'hidden_questions_deleted' => 'Slettet ^1 af ^2 skjulte spørgsmål uden pårørende...',
		'hotness_factors' => 'Relativ betydning for spørgsmålets hotness:',
		'hidden_title' => 'Skjult',
		'ip_address_pages' => 'IP addresse sider',
		'layout_title' => 'Layout',
		'link_name' => 'Linkets tekst:',
		'link_new_window' => 'Åben link i et nyt vindue',
		'link_url' => 'URL link - absolut eller relativ til Q2A rod:',
		'lists_title' => 'Lister',
		'mailing_complete' => 'Mailing er gennemført',
		'mailing_explanation' => 'Brugere vil være i stand til at afmelde på deres konto side.',
		'mailing_progress' => 'Mailing gennemført for ^1 af ^2 brugere...',
		'mailing_title' => 'Mailing',
		'mailing_unsubscribe' => 'Et afmeld link vil blive tilføjet i bunden af hver besked.',
		'maintenance_admin_only' => 'Dit websted er i ^1vedligeholdelse^2 og er i øjeblikket utilgængelig for almindelige brugere.',
		'maximum_x' => ' (maks ^)',
		'module_x_database_init' => 'x ^1 ^2 Modulet kræver en vis ^3database initialisering^4.',
		'most_flagged_title' => 'Flagged indhold',
		'mysql_version' => 'MySQL version:',
		'nav_links_explanation' => 'Vis navigationslinks:',
		'nav_qa_is_home' => 'Q&A (links til hjemmeside)',
		'neat_urls_note' => ' (kræver ^1htaccess^2 fil)',
		'no_approve_found' => 'Intet indhold venter på godkendelse',
		'no_classification' => 'Ingen',
		'no_flagged_found' => 'Ingen flagged indhold fundet',
		'no_hidden_found' => 'Ingen skjult indhold fundet',
		'no_image_gd' => 'Den installerede version af PHP blev kompileret uden GD billede støtte, så brugerne kan ikke uploade deres avatarer direkte.',
		'no_link' => 'Ingen link',
		'no_multibyte' => 'Den installerede version af PHP blev kompileret uden multibytesekvens streng støtte. Søgning vil være mindre effektive for ikke-latinske bogstaver.',
		'no_privileges' => 'Kun administratorer kan få adgang til denne side.',
		'not_logged_in' => 'Venligst ^1log ind^2 som administrator for at få adgang til denne side.',
		'opposite_main_menu' => 'Ved enden af fanerne i toppen',
		'options_reset' => 'Indstillinger nulstilles',
		'options_saved' => 'Indstillinger gemt',
		'options' => 'indstillinger',
		'page_already_used' => 'Dette er allerede brugt af en side',
		'page_content_html' => 'Indhold til at vise i side - HTML tilladt:',
		'page_default_slug' => 'side-^',
		'page_heading' => 'Overskrift at vise øverst på siden:',
		'page_name' => 'Navn på siden (også brugt til fane eller et link):',
		'page_slug' => 'Side slug (URL fragment):',
		'pages_explanation' => 'Klik på \'Tilføj side\' knappen at tilføje brugerdefineret indhold til dit Q2A websted, eller \'Tilføj Link\' for at linke til en anden webside.',
		'pages_title' => 'Sider',
    'approve_user_popup' => "Godkend bruger",
		'block_user_popup' => "Bloker bruger",
		'caching_cleanup' => "Cache oprydnings handlinger",
		'caching_delete_all' => "Slet hele cachen",
		'caching_delete_complete' => "Cache succesfuldt slettet",
		'caching_delete_expired' => "Slet forældet cache",
		'caching_delete_progress' => "Slettede ^1 of ^2 cache filer...",
		'caching_dir_error' => "Mappen ^ er defineret som QA_CACHE_DIRECTORY og kan derfor ikke ændres fra webserveren.",
		'caching_dir_missing' => "Cache mappe er ikke defineret.",
		'caching_dir_public' => "Mappen ^ er defineret som QA_CACHE_DIRECTORY og skal derfor ligge udenfor den offentlige root-mappe.",
		'caching_num_items' => "Antal emner i cachen",
		'caching_space_used' => "Samlet størrelse af cachen",
		'caching_title' => "Cacher",
		'enabled' => "Enabled",
		'memcached_error' => "Memcache fejl: ^",
		'no_memcached' => "Memcache PHP udvidelsen er ikke installeret.",
		'recalc_hotness_q_view_note' => "Kan forbedre sidens hastighed en anelse hvis slået fra, men intensitetsværdier vil blive forældede, hvis visninger inkluderes i intensitetsindstillingerne",
		'reset_options_confirm' => "Er du sikker på, at du vil nulstille alle indstillinger på denne side til defaultværdier?",
		'save_view_button' => "Gem og Se",
		'total_qs_unans' => "Samlede antal ubesvarede spørgsmål:",
		'pause_mailing_button' => 'Pause mailudsendelse',
		'per_ip_hour' => 'pr. IP/time',
		'per_user_hour' => 'pr. user/time',
		'permissions_title' => 'Rettigheder',
		'permit_to_view' => 'Synlig for:',
		'php_version' => 'PHP version:',
		'pixels' => 'pixels',
		'plugin_module' => ' (plugin modul: ^)',
		'plugin_pages_explanation' => 'Sider tilgængelige via plugin:',
		'plugins_title' => 'Plugins',
		'points_defaults_shown' => 'Standard vist nedenfor, men anvendes endnu ikke:',
		'points_required' => 'Point, der kræves for at modtage titlen:',
		'points_title' => 'Points',
		'points' => 'points',
		'position' => 'Position:',
		'posting_title' => 'Sender',
		'profile_fields' => 'Ekstra felter på brugerens profil:',
		'q2a_build_date' => 'Byg dato:',
		'q2a_db_size' => 'Database størrelse:',
		'q2a_db_version' => 'Q2A database version:',
		'q2a_latest_version' => 'Seneste version:',
		'q2a_version' => 'Question2Answer version:',
		'question_lists' => 'Spørgsmål lister',
		'question_pages' => 'Spørgsmål sider',
		'recalc_categories_backpaths' => 'Omregnes URL stier til ^1 af ^2 kategorier...',
		'recalc_categories_complete' => 'Alle kategorier blev genberegnet.',
		'recalc_categories_note' => ' - for post-kategorier og kategori tæller',
		'recalc_categories_recounting' => 'Gentæller spørgsmål for ^1 af ^2 kategorier...',
		'recalc_categories_updated' => 'Genberegnet for ^1 af ^2 indlæg...',
		'recalc_categories' => 'Genberegn kategorier',
		'recalc_points_complete' => 'Alle bruger points blev genberegnet.',
		'recalc_points_note' => ' - for bruger placering og point visning',
		'recalc_points_recalced' => 'Genberegnet for ^1 af ^2 brugere...',
		'recalc_points_usercount' => 'Anslået antal af alle brugere...',
		'recalc_points' => 'Genberegn bruger points',
		'recalc_posts_count' => 'Samlede antal spørgsmål, svar og kommentarer...',
		'recalc_stop' => 'Stop genberegningen',
		'recent_approve_title' => 'Seneste indhold venter på godkendelse',
		'recent_hidden_title' => 'Seneste skjult indhold',
		'recount_posts_as_recounted' => 'Gentalt spørgsmåls hotness for ^1 af ^2 indlæg...',
		'recount_posts_complete' => 'Alle indlæg blev gentalt.',
		'recount_posts_note' => ' - antallet af svar, afstemninger, flag og hotness for hvert indlæg',
		'recount_posts_stop' => 'Stop gentælling',
		'recount_posts_votes_recounted' => 'Gentalt stemmer og flag til ^1 af ^2 indlæg...',
		'recount_posts' => 'Gentæl indlæg',
		'refill_events_complete' => 'Alle begivenheders streams med genfyldt',
		'refill_events_note' => ' - for hver bruger\'s liste med opdateringer',
		'refill_events_refilled' => 'Udfyldt af ^1 af ^2 spørgsmål...',
		'refill_events' => 'Genfyld begivenheds streams',
		'reindex_content' => 'Re-index indhold',
		'reindex_content_note' => ' - for søgning og relateret spørgsmål foreslag',
		'reindex_content_stop' => 'Stop re-indexing',
		'reindex_pages_reindexed' => 'Re-indexed ^1 af ^2 sider...',
		'reindex_posts_complete' => 'Alle indlæg blev indekseres.',
		'reindex_posts_reindexed' => 'Re-indexed ^1 af ^2 indlæg...',
		'reindex_posts_wordcounted' => 'Gentalt ^1 af ^2 ord...',
		'requires_php_version' => 'Deaktiveret - kræver PHP ^ eller senere',
		'requires_q2a_version' => 'Deaktiveret - kræver Question2Answer ^ eller senere',
		'reset_options_button' => 'Genoptag Mailing',
		'save_options_button' => 'Gem indstillinger',
		'save_recalc_button' => 'Gem og Genberegn',
		'send_test_button' => 'Send Test til mig',
		'show_defaults_button' => 'Vis Defaults',
		'slug_bad_chars' => 'Sluggen må ikke indeholde disse tegn: ^',
		'slug_reserved' => 'Denne slug er reserveret til brug af en anden side',
		'spam_title' => 'Spam',
		'start_mailing_button' => 'Start mailudsendelse',
		'stats_title' => 'Statistik',
		'stop_recalc_warning' => 'En database oprensning kører. Hvis du lukker denne side nu, vil operationen blive afbrudt.',
		'tag_pages' => 'Tag sider',
		'tags_and_categories' => 'Tags og kategorier',
		'tags_not_shown' => 'Nogle spørgsmål har tags som ikke vil blive vist.',
		'tags' => 'Tags',
		'test_sent_to_x' => 'Test besked er blevet sendt til ^',
		'title_already_used' => 'Denne værdi bliver allerede brugt af en anden titel',
		'top_level_categories' => 'Top niveau kategorier:',
		'total_as' => 'Samlet antal svar:',
		'total_cs' => 'Samlet antal kommentarer:',
		'total_qs' => 'Samlet antal spørgsmål:',
		'unnamed_plugin' => 'Unavngiven Plugin',
		'upgrade_db' => 'Din Question2Answer database har behov for at blive ^1opgraderet^2 for denne version.',
		'url_format_note' => 'Indstillinger med ^ label arbejder for dit websted\'s konfiguration. For den bedste søgemaskine optimering (SEO), skal du bruge den første ^ valgmulighed tilgængelig.',
		'user_pages' => 'Brugers sider',
		'user_title' => 'Bruger titel - HTML tilladt:',
		'user_titles' => 'Bruger titler baseret på point:',
		'users_active' => 'Aktive brugere:',
		'users_must_have' => 'Brugere skal have',
		'users_posted' => 'Brugere som skrev:',
		'users_registered' => 'Registrerede brugere:',
		'users_title' => 'Brugere',
		'users_voted' => 'Brugere der stemte:',
		'version_get_x' => 'få ^',
		'version_requires_php' => '^1 kræver PHP ^2', 
		'version_requires_q2a' => '^1 kræver Q2A ^2', 
		'version_latest_unknown' => 'seneste ukendt',
		'version_latest' => 'seneste',
		'viewing_title' => 'Visning',
		'widget_all_pages' => 'Vis widget i denne position på alle tilgængelige sider',
		'widget_global_options' => ' - ^1indstillinger^2',
		'widget_name' => 'Navn på widget:',
		'widget_no_positions' => 'Denne widget er allerede blevet føjet til hver ledig position.',
		'widget_not_available' => 'Denne widget er ikke tilgængelig. Dette kan være fordi plugin udgiveren af widget er ikke længere installeret.',
		'widget_pages_explanation' => 'Vis widget i denne position på de følgende sider:',
		'widgets_explanation' => 'Tilgængelige widgets:',
		'blobs_directory_error' => "Biblioteket ^ defineret som QA_BLOBS_DIRECTORY er ikke skrivbart på serveren.",
		'blobs_move_complete' => "Migrering af uploadede billeder og dokumenter udført.",
		'blobs_move_moved' => "Migration ^1 af ^2 uploadede billeder og dokumenter",
		'blobs_stop' => "Stop migration",
		'blobs_to_db' => "Blobs til database",
		'blobs_to_db_note' => "- migrer alle uploadede billede og dokumenter fra disk filer til databasen",
		'blobs_to_disk' => "Blobs til disk",
		'blobs_to_disk_note' => "- migrer alle uploadede billede og dokumenter fra database filer til disken",
		'block_button' => "bloker",
		'form_security_expired' => "Sikkerhedskoden til formularen er udløbet - prøv igen",
		'approve_users_title' => "Godkend brugere",
		'no_unapproved_found' => "Der er ingen bruger der mangler godkendelse",
		'registration_fields' => "Tilføj registreringsfelter",
		'resume_mailing_button' => "Genoptag mailing",
		'show_on_register_form' => "Vis felter på registreringsformularen",		
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
