<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 svar',
		'1_comment' => '1 kommentar',
		'1_day' => '1 dag',
		'1_disliked' => '1 ikke lide',
		'1_flag' => '1 flag',
		'1_hour' => '1 time',
		'1_liked' => '1 kan lide',
		'1_minute' => '1 minut',
		'1_month' => '1 måned',
		'1_point' => '1 point',
		'1_question' => '1 spørgsmål',
		'1_second' => '1 sekund',
		'1_tag' => '1 tag',
		'1_user' => '1 bruger',
		'1_view' => '1 visning',
		'1_vote' => '1 stemme',
		'1_week' => '1 uge',
		'1_year' => '1 år',
		'add_category_x_favorites' => 'Tilføj kategori ^ til mine favoritter',
		'add_favorites' => 'Tilføj til mine favoritter',
		'add_tag_x_favorites' => 'Tilføj tag ^ til mine favoritter',
		'all_categories' => 'Alle kategorier',
		'anonymous' => 'anonymt',
		'answer_edited' => 'svar redigeret',
		'answer_reshown' => 'svar genvist',
		'answer_selected' => 'svar valgt',
		'answered_qs_in_x' => 'Mest besvaret spørgsmål i ^',
		'answered_qs_title' => 'Mest besvaret spørgsmål',
		'answered' => 'besvaret',
		'asked_related_q' => 'Relateret spurgt spørgsmål',
		'asked' => 'spurgt',
		'by_x' => 'af ^',
		'cancel_button' => 'Annuller',
		'closed' => 'lukket',
		'comment_edited' => 'kommentar redigeret',
		'comment_moved' => 'kommentar flyttet',
		'comment_reshown' => 'kommentar genvist',
		'commented' => 'kommenteret',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^day ^month, ^year',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'Jan',
		'date_month_2' => 'Feb',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Apr',
		'date_month_5' => 'Maj',
		'date_month_6' => 'Jun',
		'date_month_7' => 'Jul',
		'date_month_8' => 'Aug',
		'date_month_9' => 'Sep',
		'date_month_10' => 'Okt',
		'date_month_11' => 'Nov',
		'date_month_12' => 'Dec',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'redigeret',
		'field_required' => 'Udfyld venligst et eller andet i dette felt',
		'general_error' => 'Server fejl, prøv igen senere',
		'hidden' => 'skjult',
		'highest_users' => 'Top score brugere',
		'hot_qs_in_x' => 'Hot spørgsmål i ^',
		'hot_qs_title' => 'Hot spørgsmål',
		'image_not_read' => 'Billedet kunne ikke blive indlæst. Upload venligst en af: ^',
		'image_too_big_x_pc' => 'Dette billede er for stort. Venligst skalaer til ^% og prøv igen.',
		'in_category_x' => 'i ^',
		'ip_address_x' => 'IP adresse ^',
		'logged_in_x' => 'Hej ^',
		'max_length_x' => 'Maksimum længde er ^ karakter',
		'me' => 'mig',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Oplys venligst flere informationer - mindst ^ characters',
		'moved' => 'flyttet',
		'nav_activity' => 'Alle aktiviteter',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Stil et spørgsmål',
		'nav_categories' => 'Kategorier',
		'nav_feedback' => 'Send feedback',
		'nav_home' => 'Hjem',
		'nav_hot' => 'Populært!',
		'nav_login' => 'Log ind',
		'nav_logout' => 'Log ud',
		'nav_most_answers' => 'Mest besvaret',
		'nav_most_recent' => 'Seneste',
		'nav_most_views' => 'Flest visninger',
		'nav_most_votes' => 'Flest stemmer',
		'nav_no_answer' => 'Ingen besvarelser',
		'nav_no_selected_answer' => 'Ingen valgt besvarelser',
		'nav_no_upvoted_answer' => 'Ingen stemmer',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Spørgsmål',
		'nav_register' => 'Opret bruger',
		'nav_tags' => 'Tags',
		'nav_unanswered' => 'Ubesvaret',
		'nav_updates' => 'Mine updates',
		'nav_users' => 'Brugere',
		'no_active_users' => 'Ingen aktive brugere fundet',
		'no_answers_found' => 'Ingen svar fundet',
		'no_answers_in_x' => 'Ingen svar i ^',
		'no_categories_found' => 'Ingen kategorier fundet',
		'no_category' => 'Ingen kategori',
		'no_comments_found' => 'Ingen kommentarer fundet',
		'no_comments_in_x' => 'Ingen kommentarer i ^',
		'no_questions_found' => 'Ingen spørgsmål fundet',
		'no_questions_in_x' => 'Ingen spørgsmål i ^',
		'no_related_qs_title' => 'Ingen relateret spørgsmål fundet',
		'no_results_for_x' => 'Ingen resultater fundet for ^',
		'no_tags_found' => 'Ingen tags fundet',
		'no_una_questions_found' => 'Ingen ubesvaret spørgsmpl fundet',
		'no_una_questions_in_x' => 'Ingen ubesvarede spørgsmål i ^',
		'no_unselected_qs_found' => 'Ingen spørgsmål fundet indenfor et valgt svar',
		'no_unupvoteda_qs_found' => 'Ingen spørgsmål fundet uden en opstemt svar',
		'page_label' => 'Side:',
		'page_next' => 'næste',
		'page_not_found' => 'Side ikke fundet',
		'page_prev' => 'forrige',
		'popular_tags' => 'Mest populære tags',
		'questions_tagged_x' => 'Seneste spørgsmål tagged ^',
		'recategorized' => 'gen-kategoriseret',
		'recent_activity_in_x' => 'Senest aktivitet i ^',
		'recent_activity_title' => 'Senest aktivitet',
		'recent_as_in_x' => 'For nylig besvarede spørgsmål i ^',
		'recent_as_title' => 'Seneste besvaret spørgsmål',
		'recent_cs_in_x' => 'Senest tilføjede kommentarer i ^',
		'recent_cs_title' => 'Senest tilføjede kommentarer',
		'recent_qs_as_in_x' => 'Seneste spørgsmål og svar i ^',
		'recent_qs_as_title' => 'Seneste spørgsmål og svar',
		'recent_qs_in_x' => 'Seneste spørgsmål i ^',
		'recent_qs_title' => 'Seneste spørgsmål',
		'related_qs_title' => 'Relateret spørgsmål',
		'remove_favorites' => 'Fjern fra mine foretrukne',
		'remove_x_favorites' => 'Fjern ^ fra mine favoritter',
		'reopened' => 'genåbnet',
		'reshown' => 'genvist',
		'results_for_x' => 'Søgeresultat for ^',
		'retagged' => 'retagged',
		'save_button' => 'Gem ændringer',
		'search_button' => 'Søg',
		'search_explanation' => 'Indtast venligst noget i søge boksen og prøv at søg igen.',
		'search_title' => 'Søgeresultat',
		'selected' => 'valgt',
		'send_button' => 'Send',
		'suggest_ask' => 'Hjælp med at få tingene i gang ved at ^1stille et spørgsmål^2.',
		'suggest_category_qs' => 'Hvis du vil se mere, klik for alle ^1spørgsmål i denne kategori^2.',
		'suggest_qs_tags' => 'Hvis du vil se mere, skal du klikke for ^1fulde liste af spørgsmål^2 eller ^3populære tags^4.',
		'suggest_qs' => 'Hvis du vil se mere, skal du klikke for ^1den fulde liste af spørgsmål^2.',
		'unanswered_qs_in_x' => 'Spørgsmål uden svar i ^',
		'unanswered_qs_title' => 'Seneste spørgsmål uden svar',
		'unselected_qs_in_x' => 'Spørgsmål uden et valgt svar ^',
		'unselected_qs_title' => 'Seneste spørgsmål uden et valgt svar',
		'unupvoteda_qs_in_x' => 'Spørgsmål uden et opstemt svar ^',
		'unupvoteda_qs_title' => 'Seneste spørgsmål uden et opstemt svar',
		'upload_limit' => 'Alt for mange uploads - prøv igen om en time',
		'view_q_must_confirm' => 'Venligst ^5bekræft din email adresse^6 for at se spørgsmål siderne.',
		'view_q_must_login' => 'Venligst ^1log ind^2 eller ^3registrerer^4 for at se spørgsmål siderne.',
		'viewed_qs_in_x' => 'Mest viste spørgsmål i ^',
		'viewed_qs_title' => 'Mest viste spørgsmål',
		'vote_disabled_down' => 'Ned stemning er kun tilgængelig for nogle brugere',
		'vote_disabled_hidden_a' => 'Du kan ikke stemme på skjulte svar',
		'vote_disabled_hidden_q' => 'Du kan ikke stemme på skjulte spørgsmål',
		'vote_disabled_level' => 'Afstemningen er kun tilgængelig for nogle brugere',
		'vote_disabled_my_a' => 'Du kan ikke stemme på dine egne svar',
		'vote_disabled_my_q' => 'Du kan ikke stemme på dine egne spørgsmål',
		'vote_disabled_q_page_only' => 'Se venligst dette spørgsmål for at stemme',
		'vote_down_must_confirm' => 'Venligst ^5bekræft din email adresse^6 for at ned stemme.',
		'vote_down_popup' => 'Klik for at stemme ned',
		'vote_limit' => 'For many stemmer modtaget - prøv igen om en times tid',
		'vote_must_confirm' => 'Venligst ^5bekræft din email adresse^6 for at stemme.',
		'vote_must_login' => 'Venligst ^1log ind^2 eller ^3registrerer^4 for at stemme.',
		'vote_not_allowed' => 'Afstemning om dette er ikke tilladt',
		'vote_up_popup' => 'Klik for at stemme op',
		'voted_down_popup' => 'Du har stemt denne ned - klik for at fjerne stemme',
		'voted_qs_in_x' => 'Højeste stemte spørgsmål i ^',
		'voted_qs_title' => 'Højeste stemte spørgsmål',
		'voted_up_popup' => 'Du har stemt dette op - klik for at fjerne stemme',
		'x_ago' => '^ siden',
		'x_answers' => '^ svar',
		'x_comments' => '^ kommentarer',
		'x_days' => '^ dage',
		'x_disliked' => '^ kan ikke lide',
		'x_flags' => '^ flag',
		'x_hours' => '^ timer',
		'x_liked' => '^ kan lide',
		'x_minutes' => '^ minutter',
		'x_months' => '^ måneder',
		'x_points' => '^ point',
		'x_questions' => '^ spørgsmål',
		'x_seconds' => '^ sekunder',
		'x_tags' => '^ tags',
		'x_users' => '^ brugere',
		'x_views' => '^ visninger',
		'x_votes' => '^ stemmer',
		'x_weeks' => '^ uger',
		'x_years' => '^ år',
		'max_upload_size_x' => "Maksimal upload størrelse er ^",
		'view_q_must_be_approved' => "Din konto skal godkendes for at du kan se spørgsmål. Vent venligst eller ^1tilføj mere information^2.",
		'vote_disabled_approve' => "Din konto skal godkendes for at du kan afgive stemmer.",
		'vote_disabled_down_approve' => "Din konto skal godkendes for at du kan afgive negative stemmer.",
		'written' => "",		
		'_decimal_point' => ",",
		'_thousands_separator' => ".",
		'_thousands_suffix' => "k",
		'_millions_suffix' => "m",
		'email_error' => "En fejl er opstået i forsøget på at sende email.",
		'file_upload_limit_exceeded' => "Filens størrelse overstiger serverens grænser",
		'newest_users' => "Nyeste brugere",
		'since_x' => "siden ^",
		'to_x' => "til ^",
		'vote_disabled_hidden_post' => "Man kan ikke stemme på skjulte poster",
		'vote_disabled_my_post' => "Man kan ikke stemme på egne poster",
		'vote_disabled_queued' => "Man kan kun stemme på godkendte poster",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
